# Generated by Django 3.1.6 on 2021-02-05 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table_2',
            fields=[
                ('table_2_id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_2', models.TextField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Table_1',
            fields=[
                ('table_1_id', models.IntegerField(primary_key=True, serialize=False)),
                ('field_1', models.TextField(max_length=999)),
                ('table_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_2', to='testapp.table_2')),
            ],
        ),
    ]
